<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-7VPEI16" failures="1" tests="3" name="Surefire test" time="52.849" errors="0" timestamp="2025-05-13T12:06:48 AST">
  <testcase classname="tests.TestCase1_RegisterUser" name="testRegisterAndDeleteUser" time="30.036"/>
  <testcase classname="tests.TestCase6_ContactUsForm" name="testSendContactForm" time="7.083"/>
  <testcase classname="tests.TestCase9_SearchProduct" name="searchProductTest" time="11.303">
    <failure type="java.lang.AssertionError" message="Intentionally failing this test expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Intentionally failing this test expected [true] but found [false]
at tests.TestCase9_SearchProduct.searchProductTest(TestCase9_SearchProduct.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- searchProductTest -->
  <testcase classname="base.BaseTest" name="@BeforeSuite setAllureResultsDirectory" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setAllureResultsDirectory -->
  <testcase classname="base.BaseTest" name="@BeforeSuite setAllureResultsDirectory" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setAllureResultsDirectory -->
  <testcase classname="base.BaseTest" name="@BeforeSuite setAllureResultsDirectory" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setAllureResultsDirectory -->
</testsuite> <!-- Surefire test -->
